import results

import parser

import rules/reducer; export reducer
import rules/all

proc asl_grammar*(): Result[Grammar[ParseResult], string] =
  new_grammar[ParseResult](@[
    space,
    newline,
    underscore,
    minus,
    equal,
    comma,
    colon,
    hashtag,
    period,
    paren_open,
    paren_close,
    brace_open,
    brace_close,
    visible_character,
    eof_rule,
    digit,
    lowercase_alphabet,
    uppercase_alphabet,
    alphabet_rule,
    identifier_head_rule,
    identifier_tail_rule,
    identifier_rule,
    integer,
    keyword_arg_value_rule,
    keyword_arg_rule,
    leading_keyword_arg_rule,
    struct_rule,
    literal_rule,
    init_rule,
    arg_rule,
    leading_arg_rule,
    arglist_rule,
    fncall_rule,
    expr_rule,
    assignment_rule,
    fn_keyword,
    returns_keyword,
    args_keyword,
    arg_def_rule,
    leading_arg_def_rule,
    arg_def_list_rule,
    fn_def_rule,
    app_keyword,
    module_keyword,
    struct_keyword,
    union_keyword,
    match_keyword,
    case_keyword,
    else_keyword,
    keyword_arg_def_rule,
    leading_keyword_arg_def_rule,
    struct_def_rule,
    union_def_rule,
    app_def_rule,
    module_def_rule,
    match_def_rule,
    case_def_rule,
    else_def_rule,
    struct_macro_rule,
    union_macro_rule,
    macro_call_rule,
    statement_rule,
    comment_rule,
    line_rule,
    leading_line_rule,
    program_rule,
  ])
