name: Test ASLang

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc curl

      - name: Run test script
        run: bash test.sh
